car/config/routes.rb
Rails.application.routes.draw do
	root to: 'car_logs#home'
	get 'car_logs/home', to: 'car_logs#home'
	get 'car_logs/creator', to: 'car_logs#creator'
	get 'car_logs/new', to: 'car_logs#new'
	get 'car_logs/show', to: 'car_logs#show'

	resources :car_logs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

car/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

car/app/models/car_log.rb
class CarLog < ActiveRecord::Base

	validates :plate_number, presence:true, null:false,length: { maximum:8 }
	self.table_name = "carlogs"


end

car/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

car/app/controllers/car_logs_controller.rb
class CarLogsController < ApplicationController
	def home
		@CarLog = CarLog.last 
	end
	def new 
		@CarLog = CarLog.new
	end
	def create
		@CarLog = CarLog.new(carlog_params)
		@CarLog.save
		

		if@CarLog.save
			redirect_to car_log_path(@CarLog)
		else
			render 'new'	
		end
	end
	
	def creator
	end
	def show
		if CarLog.all.count.zero?
			flash[:notice] = "No Cars have been registered yet!"
			render 'home'
		else
		@CarLog = CarLog.last
	end
	end
	private
		def carlog_params
			params.require(:car_log).permit(:time_in, :time_out, :plate_number, :color, :brand)


		end
	
end

car/app/helpers/application_helper.rb
module ApplicationHelper
end

car/app/views/car_logs/creator.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CREATOR</title>
	<%= stylesheet_link_tag "car.css" %>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Chakra+Petch">
</head>
<body class="homebg" style="margin: 0;">
	<nav class="navbar1" class="navbar2" class="navbar3">
		<div class="navbar3">
			<%= link_to "Home", car_logs_home_path, class:'navtext'=%>
			 <%= link_to "Register", car_logs_new_path, class:'navtext'
			 =%>
			<%= link_to "View Log", car_logs_show_path, class:'navtext'=%>

		</div>
	</nav>
	<img style="float: left; width: 470px; height: auto;"  alt="Me" src="/space/oof.jpg">
	<h1 class="header">Julianne Dorothee S. Navarrete</h1>
	
	<div>
		<p class="link" style="text-align: center;">
			Hi I'm Julianne but you can call me Juls! I am 19 years old and I enjoy watching movies and reading books. I'm also a junior taking up BS Management Information Systems in Ateneo. I have an obsession with cats and memes! yeet 

			I hope you find my website useful! if not then #oof
		</p>
	</div>

</body>
</html>

car/app/views/car_logs/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
	<%= stylesheet_link_tag "car.css" %>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Chakra+Petch">
</head>
<% unless flash.empty? %>
  <div id="notice" class="link">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
<% end %>

<body class="homebg" style="margin: 0; text-align: center;">
	<nav class="navbar1" class="navbar2" class="navbar3">
		<div class="navbar3">
			 <%= link_to "About", car_logs_creator_path, class:'navtext'
			 =%>
		</div>
   
	</nav>
		<img class="center"  alt="Jupiter" src="/space/jupiter.gif">
		<h1 class="header" class="center">Welcome to Planet Parking</h1>

		<div class="center"> 
			<%= link_to "Register Car", car_logs_new_path, class: 'button'=%>
		</div>
		<div class="center">
			<%= link_to "View Log", car_logs_show_path, class:'button'=%>
		</div>

		
     

</body>
</html>

car/app/views/car_logs/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NEW CAR</title>
	<%= stylesheet_link_tag "car.css" %>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Chakra+Petch">
</head>
<body class="homebg" style="margin: 0">
	<nav class="navbar1" class="navbar2" class="navbar3">
		<div class="navbar3">
			<%= link_to "Home", car_logs_home_path, class:'navtext'=%>
			 <%= link_to "About", car_logs_creator_path, class:'navtext'
			 =%>
			<%= link_to "View Log", car_logs_show_path, class:'navtext'=%>

		</div>
   
	</nav>
	<img style="float: left;"  alt="Register" src="/space/register.jpg">
	<br>
	<br>
	
		<h1 class="header" class="center" style="display: inline; text-align:center; width:37%;float: right;">Register Car</h1>
	
	
	<% if @CarLog.errors.any? %>
	<h2 class="error">Errors:</h2>
	<ul class="error">
		<% @CarLog.errors.full_messages.each do | msg| %>
		<%= msg %>
		<% end %>
	</ul>
	<% end %>
<div class="center" style="display: inline-block;width: 37%;text-align: center;">
	<%= form_for @CarLog do |s| %>
	<p class="link" >
		<%= s.label :time_in_ %>
		<%= s.time_select :time_in %>
	</p>

	<p class="link">
		<%= s.label :time_out %>
		<%= s.time_select :time_out %>
	</p>
<div class="link"> 
	<p class="link">
		<%= s.label :plate_number %>
		<%= s.text_field :plate_number %>
	</p>
	</div>

		<p class="link">
		<%= s.label :color %>
		<%= s.select(:color, [['Red'],['Silver'],['Yellow'],['Blue'],['Black'],['White']]) %>
		</p>
		<p class="link">
		<%= s.label :brand %>
		<%= s.select(:brand, [['Honda'],['Toyota'],['BMW'],['Ford'],['Mercedes'],['Ferrari'],['Hyundai'],['Porsche']]) %>
		</p>

	<p class="link">
		<%= s.submit %>
	</p>
</div>

	<% end %>

</body>
</html>

car/app/views/car_logs/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CAR LOG</title>
	<%= stylesheet_link_tag "car.css" %>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Chakra+Petch">
</head>
<body class="homebg" style="margin: 0;">
	<nav class="navbar1" class="navbar2" class="navbar3">
		<div class="navbar3">
			<%= link_to "Home", car_logs_home_path, class:'navtext'=%>
			 <%= link_to "About", car_logs_creator_path, class:'navtext'
			 =%>
			<%= link_to "Register", car_logs_new_path, class:'navtext'=%>
		</div>
   
	</nav>
	<img style="float: right;height: auto; text-align: right; display: inline;"  alt="Log" src="/space/log.jpg">
	<div  style="display:block;width: 33%;text-align: center;">
		<br>
		<br>
		<h1 class="header">Car Registered!</h1> 
	
	<p class="link">
	TIME IN:  <%= @CarLog.time_in %>
	</p>
	<p class="link">
	TIME OUT:  <%= @CarLog.time_out %>
	</p>
	<p class="link">
	PLATE NUMBER:  <%= @CarLog.plate_number %>
	</p>
	<p class="link">
	COLOR:   <%= @CarLog.color %>
	</p>
	<p class="link">
	BRAND:   <%= @CarLog.brand %>
	</p>
	</div>
	
	

	

		


</body>
</html>

car/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>